[project]
name = "techstax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "flask>=3.1.1",
    "flask-pymongo>=3.0.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
]
